#!/bin/bash

file=~/etc/crontab
sumfile=~/sum
outp=`md5sum $file`
outp2=`cat $sumfile`
if [ "$outp" == "$outp2" ];
	then echo "file was not modified" > /dev/null
else echo "FILE WAS MODIFIED" | email -s "crontab log" root
fi
md5sum $file > $sumfile

# crontab -e 0 0 * * * ~/init/scripts/04
# sudo apt-get install mailutils for mail
